# Generated by Django 6.1 on 2026-08-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qahistory',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='qa_history', to='documents.document'),
        ),
    ]
